### ISSUE TITLE
Slow token response

### ISSUE THREAD

**Issue by ireneshr** [ireneshr/authentication#1]
Debug application to find out why the service takes ~20 secs to return a token when using H2 as the datasource (UPDATE: Doesn't Occur with MySQL)

**Comment by MauArg** [comment]
### Results
Tested in local environment and in cluster and got the following results:

- Local environment has an average response time of ~500ms
- Cluster environmnt has an average response time of ~1000ms

Both tests were performed **using my own username/password**, so the problem could be user account related

### More details

- Endpoint hit = /auth/token
- Tool = Postman
- Number of test calls = 20 (per env)

**Comment by ireneshr** [comment]
Couldn't be recreated.
It seemed to be related to the account/password
